
services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6380:6379"

  api:
    build: .
    container_name: api
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    volumes:
      - uploads:/app/uploads
      - outputs:/app/outputs

  worker_1:
    build:
      context: .
      dockerfile: app/workers/Dockerfile
    container_name: worker_1
    environment:
      - REDIS_URL=redis://redis:6379/0
      - WORKER_ID=worker_1
    depends_on:
      - redis
    volumes:
      - uploads:/app/uploads
      - outputs:/app/outputs

  worker_2:
    build:
      context: .
      dockerfile: app/workers/Dockerfile
    container_name: worker_2
    environment:
      - REDIS_URL=redis://redis:6379/0
      - WORKER_ID=worker_2
    depends_on:
      - redis
    volumes:
      - uploads:/app/uploads
      - outputs:/app/outputs

  worker_3:
    build:
      context: .
      dockerfile: app/workers/Dockerfile
    container_name: worker_3
    environment:
      - REDIS_URL=redis://redis:6379/0
      - WORKER_ID=worker_3
    depends_on:
      - redis
    volumes:
      - uploads:/app/uploads
      - outputs:/app/outputs

volumes:
  uploads:
  outputs:
